### PR TITLE
complete rev1 refactoring and init

### PR DESCRIPTION
**Pull request by tuilagio**
This is a fucking big pull request:
# Important
I removed/commnted out some line in route area in ``main.rs``. Check your work if you used to touch those!

Also, pls, clone my repo `git clone https://github.com/tuilagio/tagify-backend` and take a look! Use `insomnia_rev1.json` to view API documentation.

Some useful cmd:
``` bash
# rust output log is fking long and not useful. Export to txt file to view full version uncensor.
cargo run 1> terminal_output.txt 2>&1
# pg container for testing. change postgres host in Settings.toml to correct url if needed.
docker container stop pg_tagify; docker container prune; docker run --name pg_tagify -e POSTGRES_USER=example -e POSTGRES_PASSWORD=example -e POSTGRES_DB=example -d -p 5432:5432 library/postgres
# of course:
cargo run
```

# SQL remake:
- Add 2 default users: `admin` and `user1` (role ``tagger``) with `password` as password. Also adapt column in `users` table.
- We should not do SQL anywhere else except in this file **`src/db.rs`**

BEFORE:
``` rust
// execute db query
// Query data
let result = client
    .execute(
        "INSERT INTO users (username, nickname, password, is_admin) VALUES ($1,$2,$3,$4)",
        &[
            &admin.username,
            &admin.nickname,
            &admin.password,
            &admin.is_admin,
        ],
    )
    .await;
```
AFTER:
```rust
let user = db::get_internal_user_with_id(&client, &user_id).await;
    match user {
        Ok(u) => Ok(HttpResponse::Ok()
            .content_type("application/json")
            .body(json!({
                "id": u.id,
                "username": u.username,
                "nickname": u.nickname,
                "role": u.role,
            }))
        ),
        Err(e) => {
            println!("{:?}", e);
            return Err(CutomResponseError::InternalError)
        },

    }
```
# Models:
- Change SQL schema for users: instead of  <Bool>`is_admin` now we have <String>`role`. Role can be _"admin"_ or _"tagger"_. This can also be extended later (in `db::ROLES`)
- Generally, each object type has 2 models: 1 for receiving from client (i.e: `User` without `id` field) and 1 for internal use (`InternalUser`, with other field like "id" or maybe other sensitive, manage-purpose fields). I refactoried `User` model and do some small changes here and there.

... also add `...... RETURNING *` to the end of query (execute usually with `client.query_one`) so we get the effected row returned.

# Somewhere to put stuffs
- We put usefull functions in **`src/utils.rs`**.

# APIs
A lot of changes in this topic, in 2 sentences
- No different API path between admin and user. Permission should be handled by cookies + middleware.
- Read the ***`Insomnia_rev1.json`*** for new API structure!

# How locking works
Procedure to work with image
- An image has a meta. Meta holds meta data (date time, filename, id, ...) and tag list.
- Create, or in other word, upload a image: 
  + POST meta to receive img_id for image. 
  + Then send a POST request to `/api/albums/<:album_id>/images/<img_id>` to upload.
- Re-create image: send PUT to images/<img_id>. server will silently replace old img.
- Lock: 
    + The moment a tagger clicks mouse on tag input form, the lock request is sent. Server remember who created the lock and when. 
        + If there is no lock for this img he will receive a 200-accept from server. His frontend can implement a countdown or not, just to inform him. 
           He can also send a unlock request to tell server he doesn't want to submit anything yet to delete his lock.
           While holding the lock the tagger can also send lock request again to extend. Think about Berlin Wohnung Mieter!
    + Else, 423-Locked. He better waits!
    + In the mean time: Any PUT or POST request to upload tags will be check: 
        + if timeout from last lock for this img still lasts => only request from this tagger gets accept, other gets 403-Forbidden. 
          Server deletes this lock after applying his submit.
        + else if timeout past (or no lock at all) ANY request will be accepted (without sending lock request first) and lock gets deleted.

# What haven't been done:
- Lots of small optimizations.
- How to really upload/download a file. Base64 encode to fit in `json` request body, or how?
- API. The URLs are considered to be pretty reliable, but after many tests done by me some ``json`` fiels/values have been changed. And this is my work alone, cannot avoid idiot or senselos decisions!

### CODE REVIEW

**Comment by Luis-Hebendanz** [comment]
Sweet! I looked into it and the api looks good :+1:  On Tuesday I will merge the commit. One thing I would change is to combine CustomResponseError and UserError into one error struct. And remove the WeFuckedUp error because that's the role of the InternalError basically :)

**Comment by tuilagio** [comment]
`to combine CustomResponseError and UserError into one error struct` 
Yeah the official Rust doc also stated that sometimes its better to have just an enum error instead of boxing. The  CustomResponseError contains all element of UserError. I think I will rename the `CustomResponseError ` to simple `CustomError `. Any suggest?

**Comment by Luis-Hebendanz** [comment]
CustomError is too generic, I would suggest to use HandlerError as this Error enum should only be used in handlers.

**Comment by tuilagio** [comment]
> 
> 
> CustomError is too generic, I would suggest to use HandlerError as this Error enum should only be used in handlers.

Fixed. How to resolve conflict? from your side or should I do it?

**Comment by Luis-Hebendanz** [comment]
I will do it

**Comment by Luis-Hebendanz** [comment]
Hmm hast du jemals deinen Code getestet? Ich sehe unglaublich viele fehler im Code

**Comment by Luis-Hebendanz** [comment]
I made a new branch and copied parts of your pull request there while also changing other stuff so don't be surprised by the fact that I close this pull request it still has been (partially) applied

**Pull request closed without merging**
